package control.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;

import javax.swing.*;


/**
 * User interface class (JPanel) responsible for control of commands not generated by CommandComposer. Commands include:
 * <ul>
 * <li> Autonomous Mode
 * <li> Halt All Actions
 * <li> Power Down
 * <li> Reset
 * </ul>
 * Commands are controlled by various GUI elements present in this panel.
 * @author Steph
 */
public class OtherCommands extends JPanel{

	/**
	 * Title label for panel, to read: "Other Commands"
	 */
	private JLabel otherLabel;
	
	/**
	 * JCheckBox object to signify Autonomous Mode
	 */
	private JCheckBox autonomous;
	
	/**
	 * JButton to issue "Halt All Actions" command
	 */
	private JButton halt;
	
	/**
	 * JButton to issue "Power Down" command
	 */
	private JButton power;
	
	/**
	 * JButton to issue "Reset" command
	 */
	private JButton reset;
	
	/**
	 * Default Constructor for OtherCommands.
	 * <p>
	 * Set appearance of OtherCommands panel, initialize and assign functionality
	 * to the various GUI component fields
	 */
	public OtherCommands() {
		
		// Set size and layout of panel
		setPreferredSize(new Dimension(250, 160));
		setLayout(new FlowLayout(FlowLayout.LEADING, 8, 3));
		
		// Set title label for panel
		otherLabel = new JLabel("Other Commands");
		otherLabel.setFont(new Font("Arial", Font.BOLD, 15));
		
		// Initialize autonomous mode JCheckBox
		autonomous = new JCheckBox("Autonomous Mode");
		autonomous.setFont(new Font("Arial", Font.PLAIN, 14));
		
		// Initialize command JButtons and set their style
		halt = new JButton("Halt All Actions");
		halt.setFont(new Font("Arial", Font.PLAIN, 14));
		halt.setPreferredSize(new Dimension(235, 33));
		
		power = new JButton("Power Down");
		power.setFont(new Font("Arial", Font.PLAIN, 14));
		power.setPreferredSize(new Dimension(235, 33));
		
		reset = new JButton("Reset");
		reset.setFont(new Font("Arial", Font.PLAIN, 14));
		reset.setPreferredSize(new Dimension(235, 33));
		
		// Add all components to main panel
		add(otherLabel);
		add(autonomous);
		add(halt);
		add(power);
		add(reset);
		
	}
	
		
	/**
	 * Simple Getter
	 * @return {@link OtherCommands#autonomous} (JCheckBox object to signify Autonomous Mode)
	 */
	public JCheckBox getAutonomous() {
		return autonomous;
	}
	
	/**
	 * Simple Getter
	 * @return {@link OtherCommands#halt} (JButton to issue "Halt All Actions" command)
	 */
	public JButton getHalt() {
		return halt;
	}
	
	/**
	 * Simple Getter
	 * @return {@link OtherCommands#power} (JButton to issue "Power Down" command)
	 */
	public JButton getPower() {
		return power;
	}
	
	/**
	 * Simple Getter
	 * @return {@link OtherCommands#reset} (JButton to issue "Reset" command)
	 */
	public JButton getReset() {
		return reset;
	}
}
